# Generated by Django 2.2.16 on 2020-09-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_file", models.FileField(upload_to="characters/")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
